# QUESTION1

In [1]:
import numpy as np 
  
# Printing all numbers starting from 2 to 50 with stepsize of 3 
print(np.arange(2, 50, 3))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# QUESTION2

In [26]:
l1=[]
l2=[]
n=5
for i in range(1,n+1):
    #first list
    num1=int(input())
    l1.append(num1 )
    
print("second list")
for i in range(1,n+1):
    
    num2=int(input())
    l2.append(num2) 
    

farr = np.array(l1)
sarr = np.array(l2)
print("first list:\n",farr)
print("second list:\n",sarr)
Concat_arr = np.concatenate((farr, sarr), axis=0)
print("Concatenated array ", Concat_arr)
Concat_arr.sort()
print("Sorted Array ", Concat_arr)

1
2
3
4
5
second list
6
7
8
9
1
first list:
 [1 2 3 4 5]
second list: [6 7 8 9 1]
Concatenated array  [1 2 3 4 5 6 7 8 9 1]
Sorted Array  [1 1 2 3 4 5 6 7 8 9]


# QUESTION3

In [3]:
arr2 = np.array([[1 ,2,3,8], [4, 5,7,14], [10,12,13,11]])
print(arr2)
Rows = np.size(arr2, 0)
Columns = np.size(arr2, 1)
print('Number of Rows : ', Rows)
print('Number of Columns : ', Columns)

[[ 1  2  3  8]
 [ 4  5  7 14]
 [10 12 13 11]]
Number of Rows :  3
Number of Columns :  4


# QUESTION4

In [41]:
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9,10])
arrnew=np.expand_dims(arr1, axis=0)
print(arrnew.reshape(2,5))

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


# QUESTION5

In [16]:
a = np.array([[11, 22], 
              [33, 44]]) 
  
b = np.array([[15, 26], 
              [17, 8]]) 
  
# vertical stacking 
print("Vertical stacking:\n", np.vstack((a, b))) 
  
# horizontal stacking 
print("\nHorizontal stacking:\n", np.hstack((a, b)))

Vertical stacking:
 [[11 22]
 [33 44]
 [15 26]
 [17  8]]

Horizontal stacking:
 [[11 22 15 26]
 [33 44 17  8]]


# QUESTION6

In [28]:
def unique(list1): 
    a = np.array(list1) 
    print(np.unique(a)) 
      
# driver code 
list1 = [1, 2, 5, 2, 1, 3]  
unique(list1) 
  
# converting our list to set 
set1 = set(list1) 
print("No of unique items:", len(set1))

[1 2 3 5]
No of unique items: 4
